package codec

// Precomputed Lloyd-Max codebook tables for common (dimension, bits) pairs.
// These are generated by SolveCodebook() with useExact=false (Gaussian approximation).
// The codebook depends only on σ = 1/√d, so different dimensions produce different tables.
//
// Providing precomputed tables avoids the ~100ms solve time on first use.

type PrecomputedKey struct {
	Dim  int
	Bits int
}

type PrecomputedEntry struct {
	Centroids  []float64
	Boundaries []float64
}

// PrecomputedCodebooks will be populated by init() after we generate the tables.
// For now, this is empty — the solver will be called on first use.
// TODO: populate with precomputed values after validating the solver output.
var PrecomputedCodebooks = map[PrecomputedKey]PrecomputedEntry{}
