package codec

// Precomputed Lloyd-Max codebook tables for common (dimension, bits) pairs.
// These are generated by SolveCodebook() with useExact=false (Gaussian approximation).
// The codebook depends only on σ = 1/√d, so different dimensions produce different tables.
//
// Providing precomputed tables avoids the ~100ms solve time on first use.

type PrecomputedKey struct {
	Dim  int
	Bits int
}

type PrecomputedEntry struct {
	Centroids  []float64
	Boundaries []float64
}

// PrecomputedCodebooks is empty — the solver runs on first use (~10ms).
// Precomputed tables can be added here for common (dim, bits) pairs to
// skip the solve step.
var PrecomputedCodebooks = map[PrecomputedKey]PrecomputedEntry{}
