//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.

package asm

import "unsafe"

//go:noescape
func dot_neon(a, b, res, len unsafe.Pointer)

//go:noescape
func neg_dot_neon(a, b, res, len unsafe.Pointer)

//go:noescape
func l2_neon(a, b, res, len unsafe.Pointer)
