//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.

TEXT ·dot_prefetch_neon(SB), $0-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD res+16(FP), R2
	MOVD len+24(FP), R3
	MOVD next_a+32(FP), R4
	MOVD next_b+40(FP), R5
	WORD $0xb4000044       // cbz	x4, .LBB0_2
	WORD $0xf9800080       // prfm	pldl1keep, [x4]

LBB0_2:
	WORD $0xb4000045 // cbz	x5, .LBB0_4
	WORD $0xf98000a0 // prfm	pldl1keep, [x5]

LBB0_4:
	WORD $0xa9bf7bfd // stp	x29, x30, [sp,
	WORD $0xf9400069 // ldr	x9, [x3]
	WORD $0x910003fd // mov	x29, sp
	WORD $0x6b0903e8 // negs	w8, w9
	WORD $0x1200052a // and	w10, w9,
	WORD $0x12000508 // and	w8, w8,
	WORD $0x5a884548 // csneg	w8, w10, w8, mi
	WORD $0x4b08012a // sub	w10, w9, w8
	WORD $0x7100415f // cmp	w10,
	WORD $0x540000ea // b.ge	.LBB0_6
	WORD $0x6f00e402 // movi	v2.2d,
	WORD $0x6f00e403 // movi	v3.2d,
	WORD $0x2a1f03eb // mov	w11, wzr
	WORD $0x6f00e401 // movi	v1.2d,
	WORD $0x6f00e400 // movi	v0.2d,
	WORD $0x14000057 // b	.LBB0_25

LBB0_6:
	WORD $0x6f00e400 // movi	v0.2d,
	WORD $0x6f00e401 // movi	v1.2d,
	WORD $0xaa1f03eb // mov	x11, xzr
	WORD $0x6f00e403 // movi	v3.2d,
	WORD $0x6f00e402 // movi	v2.2d,
	WORD $0xb4000364 // cbz	x4, .LBB0_13
	WORD $0x9104008c // add	x12, x4,
	WORD $0xb40005c5 // cbz	x5, .LBB0_18
	WORD $0x910400ad // add	x13, x5,
	WORD $0xaa0003ee // mov	x14, x0
	WORD $0xaa0103ef // mov	x15, x1
	WORD $0x1400000e // b	.LBB0_10

LBB0_9:
	WORD $0x4cdf29c4 // ld1	{ v4.4s, v5.4s, v6.4s, v7.4s }, [x14],
	WORD $0x91008171 // add	x17, x11,
	WORD $0x4cdf29f0 // ld1	{ v16.4s, v17.4s, v18.4s, v19.4s }, [x15],
	WORD $0x91004170 // add	x16, x11,
	WORD $0xeb0a023f // cmp	x17, x10
	WORD $0x9101018c // add	x12, x12,
	WORD $0x910101ad // add	x13, x13,
	WORD $0xaa1003eb // mov	x11, x16
	WORD $0x4e24ce00 // fmla	v0.4s, v16.4s, v4.4s
	WORD $0x4e25ce21 // fmla	v1.4s, v17.4s, v5.4s
	WORD $0x4e26ce43 // fmla	v3.4s, v18.4s, v6.4s
	WORD $0x4e27ce62 // fmla	v2.4s, v19.4s, v7.4s
	WORD $0x540000c8 // b.hi	.LBB0_12

LBB0_10:
	WORD $0xf101fd7f // cmp	x11,
	WORD $0x54fffe48 // b.hi	.LBB0_9
	WORD $0xf9800180 // prfm	pldl1keep, [x12]
	WORD $0xf98001a0 // prfm	pldl1keep, [x13]
	WORD $0x17ffffef // b	.LBB0_9

LBB0_12:
	WORD $0x2a1003eb // mov	w11, w16
	WORD $0x14000037 // b	.LBB0_25

LBB0_13:
	WORD $0xb4000545 // cbz	x5, .LBB0_23
	WORD $0x910400ac // add	x12, x5,
	WORD $0xaa0103ed // mov	x13, x1
	WORD $0xaa0003ee // mov	x14, x0
	WORD $0x1400000d // b	.LBB0_16

LBB0_15:
	WORD $0x4cdf29c4 // ld1	{ v4.4s, v5.4s, v6.4s, v7.4s }, [x14],
	WORD $0x91008170 // add	x16, x11,
	WORD $0x4cdf29b0 // ld1	{ v16.4s, v17.4s, v18.4s, v19.4s }, [x13],
	WORD $0x9100416f // add	x15, x11,
	WORD $0xeb0a021f // cmp	x16, x10
	WORD $0x9101018c // add	x12, x12,
	WORD $0xaa0f03eb // mov	x11, x15
	WORD $0x4e24ce00 // fmla	v0.4s, v16.4s, v4.4s
	WORD $0x4e25ce21 // fmla	v1.4s, v17.4s, v5.4s
	WORD $0x4e26ce43 // fmla	v3.4s, v18.4s, v6.4s
	WORD $0x4e27ce62 // fmla	v2.4s, v19.4s, v7.4s
	WORD $0x54000308 // b.hi	.LBB0_22

LBB0_16:
	WORD $0xf101fd7f // cmp	x11,
	WORD $0x54fffe68 // b.hi	.LBB0_15
	WORD $0xf9800180 // prfm	pldl1keep, [x12]
	WORD $0x17fffff1 // b	.LBB0_15

LBB0_18:
	WORD $0xaa0103ed // mov	x13, x1
	WORD $0xaa0003ee // mov	x14, x0
	WORD $0x1400000d // b	.LBB0_20

LBB0_19:
	WORD $0x4cdf29c4 // ld1	{ v4.4s, v5.4s, v6.4s, v7.4s }, [x14],
	WORD $0x91008170 // add	x16, x11,
	WORD $0x4cdf29b0 // ld1	{ v16.4s, v17.4s, v18.4s, v19.4s }, [x13],
	WORD $0x9100416f // add	x15, x11,
	WORD $0xeb0a021f // cmp	x16, x10
	WORD $0x9101018c // add	x12, x12,
	WORD $0xaa0f03eb // mov	x11, x15
	WORD $0x4e24ce00 // fmla	v0.4s, v16.4s, v4.4s
	WORD $0x4e25ce21 // fmla	v1.4s, v17.4s, v5.4s
	WORD $0x4e26ce43 // fmla	v3.4s, v18.4s, v6.4s
	WORD $0x4e27ce62 // fmla	v2.4s, v19.4s, v7.4s
	WORD $0x540000a8 // b.hi	.LBB0_22

LBB0_20:
	WORD $0xf101fd7f // cmp	x11,
	WORD $0x54fffe68 // b.hi	.LBB0_19
	WORD $0xf9800180 // prfm	pldl1keep, [x12]
	WORD $0x17fffff1 // b	.LBB0_19

LBB0_22:
	WORD $0x2a0f03eb // mov	w11, w15
	WORD $0x1400000d // b	.LBB0_25

LBB0_23:
	WORD $0xaa0103ec // mov	x12, x1
	WORD $0xaa0003ed // mov	x13, x0

LBB0_24:
	WORD $0x4cdf29a4 // ld1	{ v4.4s, v5.4s, v6.4s, v7.4s }, [x13],
	WORD $0x9100816e // add	x14, x11,
	WORD $0x4cdf2990 // ld1	{ v16.4s, v17.4s, v18.4s, v19.4s }, [x12],
	WORD $0xeb0a01df // cmp	x14, x10
	WORD $0x9100416b // add	x11, x11,
	WORD $0x4e24ce00 // fmla	v0.4s, v16.4s, v4.4s
	WORD $0x4e25ce21 // fmla	v1.4s, v17.4s, v5.4s
	WORD $0x4e26ce43 // fmla	v3.4s, v18.4s, v6.4s
	WORD $0x4e27ce62 // fmla	v2.4s, v19.4s, v7.4s
	WORD $0x54fffee9 // b.ls	.LBB0_24

LBB0_25:
	WORD $0x6b0a017f // cmp	w11, w10
	WORD $0x540001aa // b.ge	.LBB0_28
	WORD $0x2a0b03ec // mov	w12, w11
	WORD $0x93407d4a // sxtw	x10, w10
	WORD $0x2a0b03eb // mov	w11, w11
	WORD $0xd37e7d8d // ubfiz	x13, x12,
	WORD $0x8b0d002c // add	x12, x1, x13
	WORD $0x8b0d000d // add	x13, x0, x13

LBB0_27:
	WORD $0x3cc105a4 // ldr	q4, [x13],
	WORD $0x9100116b // add	x11, x11,
	WORD $0x3cc10585 // ldr	q5, [x12],
	WORD $0xeb0a017f // cmp	x11, x10
	WORD $0x4e24cca0 // fmla	v0.4s, v5.4s, v4.4s
	WORD $0x54ffff6b // b.lt	.LBB0_27

LBB0_28:
	WORD $0x4e20d420 // fadd	v0.4s, v1.4s, v0.4s
	WORD $0x4e23d441 // fadd	v1.4s, v2.4s, v3.4s
	WORD $0x7100051f // cmp	w8,
	WORD $0x4e20d420 // fadd	v0.4s, v1.4s, v0.4s
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0x7e30d800 // faddp	s0, v0.2s
	WORD $0x5400064b // b.lt	.LBB0_34
	WORD $0x93407d29 // sxtw	x9, w9
	WORD $0x4b0803ec // neg	w12, w8
	WORD $0xcb08012a // sub	x10, x9, x8
	WORD $0x9100054b // add	x11, x10,
	WORD $0xeb09017f // cmp	x11, x9
	WORD $0x9a8ad52a // csinc	x10, x9, x10, le
	WORD $0x8b08014a // add	x10, x10, x8
	WORD $0xcb09014b // sub	x11, x10, x9
	WORD $0x8b2cc12a // add	x10, x9, w12, sxtw
	WORD $0xf100217f // cmp	x11,
	WORD $0x54000423 // b.lo	.LBB0_33
	WORD $0xd37ef52c // lsl	x12, x9,
	WORD $0x927df16e // and	x14, x11,
	WORD $0xcb28c98c // sub	x12, x12, w8, sxtw
	WORD $0x927df168 // and	x8, x11,
	WORD $0x8b08014a // add	x10, x10, x8
	WORD $0x9100418d // add	x13, x12,
	WORD $0x8b0d000c // add	x12, x0, x13
	WORD $0x8b0d002d // add	x13, x1, x13

LBB0_31:
	WORD $0xad7f91a1 // ldp	q1, q4, [x13,
	WORD $0xf10021ce // subs	x14, x14,
	WORD $0xad7f8d82 // ldp	q2, q3, [x12,
	WORD $0x9100818c // add	x12, x12,
	WORD $0x910081ad // add	x13, x13,
	WORD $0x6e21dc41 // fmul	v1.4s, v2.4s, v1.4s
	WORD $0x5e0c0422 // mov	s2, v1.s[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e140425 // mov	s5, v1.s[2]
	WORD $0x5e1c0421 // mov	s1, v1.s[3]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x6e24dc62 // fmul	v2.4s, v3.4s, v4.4s
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x5e140443 // mov	s3, v2.s[2]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e0c0441 // mov	s1, v2.s[1]
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x5e1c0441 // mov	s1, v2.s[3]
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x54fffd61 // b.ne	.LBB0_31
	WORD $0xeb08017f // cmp	x11, x8
	WORD $0x540000e0 // b.eq	.LBB0_34

LBB0_33:
	WORD $0xbc6a7801 // ldr	s1, [x0, x10, lsl
	WORD $0xbc6a7822 // ldr	s2, [x1, x10, lsl
	WORD $0x9100054a // add	x10, x10,
	WORD $0xeb09015f // cmp	x10, x9
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	WORD $0x54ffff6b // b.lt	.LBB0_33

LBB0_34:
	WORD $0xbd000040 // str	s0, [x2]
	WORD $0xa8c17bfd // ldp	x29, x30, [sp],
	RET
