//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.

TEXT ·vec_mul_f64(SB), $0-32
	MOVD dst+0(FP), R0
	MOVD a+8(FP), R1
	MOVD b+16(FP), R2
	MOVD len+24(FP), R3
	WORD $0xa9bf7bfd    // stp	x29, x30, [sp,
	WORD $0xf9400068    // ldr	x8, [x3]
	WORD $0x910003fd    // mov	x29, sp
	WORD $0x12000109    // and	w9, w8,
	WORD $0x7100011f    // cmp	w8,
	WORD $0x5a895529    // cneg	w9, w9, mi
	WORD $0x4b090109    // sub	w9, w8, w9
	WORD $0x7100213f    // cmp	w9,
	WORD $0x540000aa    // b.ge	.LBB0_2
	WORD $0x2a1f03ea    // mov	w10, wzr
	WORD $0x6b09015f    // cmp	w10, w9
	WORD $0x540002cb    // b.lt	.LBB0_5
	WORD $0x14000021    // b	.LBB0_8

LBB0_2:
	WORD $0x9100802a // add	x10, x1,
	WORD $0x9100800b // add	x11, x0,
	WORD $0x9100804d // add	x13, x2,
	WORD $0x5280010c // mov	w12,

LBB0_3:
	WORD $0xad7f0da0 // ldp	q0, q3, [x13,
	WORD $0x9100218c // add	x12, x12,
	WORD $0xad7f0941 // ldp	q1, q2, [x10,
	WORD $0xeb09019f // cmp	x12, x9
	WORD $0xacc219a4 // ldp	q4, q6, [x13],
	WORD $0x6e60dc20 // fmul	v0.2d, v1.2d, v0.2d
	WORD $0x6e63dc42 // fmul	v2.2d, v2.2d, v3.2d
	WORD $0xacc21541 // ldp	q1, q5, [x10],
	WORD $0x6e64dc21 // fmul	v1.2d, v1.2d, v4.2d
	WORD $0x6e66dca3 // fmul	v3.2d, v5.2d, v6.2d
	WORD $0xad3f0960 // stp	q0, q2, [x11,
	WORD $0xac820d61 // stp	q1, q3, [x11],
	WORD $0x54fffe89 // b.ls	.LBB0_3
	WORD $0x5100218a // sub	w10, w12,
	WORD $0x6b09015f // cmp	w10, w9
	WORD $0x540001aa // b.ge	.LBB0_8

LBB0_5:
	WORD $0xd37d7d4d // ubfiz	x13, x10,
	WORD $0x2a0a03ea // mov	w10, w10
	WORD $0x8b0d000b // add	x11, x0, x13
	WORD $0x8b0d004c // add	x12, x2, x13
	WORD $0x8b0d002d // add	x13, x1, x13

LBB0_6:
	WORD $0x3cc105a0 // ldr	q0, [x13],
	WORD $0x9100094a // add	x10, x10,
	WORD $0x3cc10581 // ldr	q1, [x12],
	WORD $0xeb09015f // cmp	x10, x9
	WORD $0x6e61dc00 // fmul	v0.2d, v0.2d, v1.2d
	WORD $0x3c810560 // str	q0, [x11],
	WORD $0x54ffff43 // b.lo	.LBB0_6

LBB0_8:
	WORD $0x6b08015f // cmp	w10, w8
	WORD $0x5400022a // b.ge	.LBB0_12
	WORD $0x2a0803e8 // mov	w8, w8
	WORD $0x2a0a03ea // mov	w10, w10
	WORD $0xcb0a0109 // sub	x9, x8, x10
	WORD $0xf100193f // cmp	x9,
	WORD $0x540001c2 // b.hs	.LBB0_13

LBB0_10:
	WORD $0xd37df14c // lsl	x12, x10,
	WORD $0xcb0a0108 // sub	x8, x8, x10
	WORD $0x8b0c0009 // add	x9, x0, x12
	WORD $0x8b0c004b // add	x11, x2, x12
	WORD $0x8b0c002c // add	x12, x1, x12

LBB0_11:
	WORD $0xfc408580 // ldr	d0, [x12],
	WORD $0xf1000508 // subs	x8, x8,
	WORD $0xfc408561 // ldr	d1, [x11],
	WORD $0x1e610800 // fmul	d0, d0, d1
	WORD $0xfc008520 // str	d0, [x9],
	WORD $0x54ffff61 // b.ne	.LBB0_11

LBB0_12:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp],
	RET

LBB0_13:
	WORD $0xcb01000b // sub	x11, x0, x1
	WORD $0xf100817f // cmp	x11,
	WORD $0x54fffe23 // b.lo	.LBB0_10
	WORD $0xcb02000b // sub	x11, x0, x2
	WORD $0xf100817f // cmp	x11,
	WORD $0x54fffdc3 // b.lo	.LBB0_10
	WORD $0xd37df14c // lsl	x12, x10,
	WORD $0x927ef52b // and	x11, x9,
	WORD $0x927ef52f // and	x15, x9,
	WORD $0x8b0a016a // add	x10, x11, x10
	WORD $0x9100418e // add	x14, x12,
	WORD $0x8b0e002c // add	x12, x1, x14
	WORD $0x8b0e000d // add	x13, x0, x14
	WORD $0x8b0e004e // add	x14, x2, x14

LBB0_16:
	WORD $0xad7f8dc0 // ldp	q0, q3, [x14,
	WORD $0xf10011ef // subs	x15, x15,
	WORD $0xad7f8981 // ldp	q1, q2, [x12,
	WORD $0x9100818c // add	x12, x12,
	WORD $0x910081ce // add	x14, x14,
	WORD $0x6e60dc20 // fmul	v0.2d, v1.2d, v0.2d
	WORD $0x6e63dc41 // fmul	v1.2d, v2.2d, v3.2d
	WORD $0xad3f85a0 // stp	q0, q1, [x13,
	WORD $0x910081ad // add	x13, x13,
	WORD $0x54fffee1 // b.ne	.LBB0_16
	WORD $0xeb0b013f // cmp	x9, x11
	WORD $0x54fffb41 // b.ne	.LBB0_10
	WORD $0x17ffffe4 // b	.LBB0_12

TEXT ·vec_scale_f64(SB), $0-32
	MOVD dst+0(FP), R0
	MOVD a+8(FP), R1
	MOVD scalar+16(FP), R2
	MOVD len+24(FP), R3
	WORD $0xa9bf7bfd       // stp	x29, x30, [sp,
	WORD $0xf9400068       // ldr	x8, [x3]
	WORD $0xfd400040       // ldr	d0, [x2]
	WORD $0x910003fd       // mov	x29, sp
	WORD $0x12000109       // and	w9, w8,
	WORD $0x7100011f       // cmp	w8,
	WORD $0x5a895529       // cneg	w9, w9, mi
	WORD $0x4b090109       // sub	w9, w8, w9
	WORD $0x7100213f       // cmp	w9,
	WORD $0x540000aa       // b.ge	.LBB1_2
	WORD $0x2a1f03ea       // mov	w10, wzr
	WORD $0x6b09015f       // cmp	w10, w9
	WORD $0x5400026b       // b.lt	.LBB1_5
	WORD $0x1400001c       // b	.LBB1_8

LBB1_2:
	WORD $0x9100802a // add	x10, x1,
	WORD $0x9100800c // add	x12, x0,
	WORD $0x5280010b // mov	w11,

LBB1_3:
	WORD $0xad7f0941 // ldp	q1, q2, [x10,
	WORD $0x9100216b // add	x11, x11,
	WORD $0xacc21143 // ldp	q3, q4, [x10],
	WORD $0xeb09017f // cmp	x11, x9
	WORD $0x4fc09021 // fmul	v1.2d, v1.2d, v0.d[0]
	WORD $0x4fc09042 // fmul	v2.2d, v2.2d, v0.d[0]
	WORD $0x4fc09063 // fmul	v3.2d, v3.2d, v0.d[0]
	WORD $0x4fc09084 // fmul	v4.2d, v4.2d, v0.d[0]
	WORD $0xad3f0981 // stp	q1, q2, [x12,
	WORD $0xac821183 // stp	q3, q4, [x12],
	WORD $0x54fffec9 // b.ls	.LBB1_3
	WORD $0x5100216a // sub	w10, w11,
	WORD $0x6b09015f // cmp	w10, w9
	WORD $0x5400016a // b.ge	.LBB1_8

LBB1_5:
	WORD $0xd37d7d4c // ubfiz	x12, x10,
	WORD $0x2a0a03ea // mov	w10, w10
	WORD $0x8b0c000b // add	x11, x0, x12
	WORD $0x8b0c002c // add	x12, x1, x12

LBB1_6:
	WORD $0x3cc10581 // ldr	q1, [x12],
	WORD $0x9100094a // add	x10, x10,
	WORD $0xeb09015f // cmp	x10, x9
	WORD $0x4fc09021 // fmul	v1.2d, v1.2d, v0.d[0]
	WORD $0x3c810561 // str	q1, [x11],
	WORD $0x54ffff63 // b.lo	.LBB1_6

LBB1_8:
	WORD $0x6b08015f // cmp	w10, w8
	WORD $0x5400020a // b.ge	.LBB1_12
	WORD $0x2a0803e8 // mov	w8, w8
	WORD $0x2a0a03e9 // mov	w9, w10
	WORD $0xcb09010a // sub	x10, x8, x9
	WORD $0xf100295f // cmp	x10,
	WORD $0x540001a2 // b.hs	.LBB1_13

LBB1_10:
	WORD $0xd37df12b // lsl	x11, x9,
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0x8b0b000a // add	x10, x0, x11
	WORD $0x8b0b002b // add	x11, x1, x11

LBB1_11:
	WORD $0xfc408560 // ldr	d0, [x11],
	WORD $0xfd400041 // ldr	d1, [x2]
	WORD $0xf1000508 // subs	x8, x8,
	WORD $0x1e610800 // fmul	d0, d0, d1
	WORD $0xfc008540 // str	d0, [x10],
	WORD $0x54ffff61 // b.ne	.LBB1_11

LBB1_12:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp],
	RET

LBB1_13:
	WORD $0xd37df12c // lsl	x12, x9,
	WORD $0xd37df10b // lsl	x11, x8,
	WORD $0x9100204e // add	x14, x2,
	WORD $0x8b0c000d // add	x13, x0, x12
	WORD $0x8b0b000f // add	x15, x0, x11
	WORD $0x8b0b0030 // add	x16, x1, x11
	WORD $0xeb0e01bf // cmp	x13, x14
	WORD $0x8b0c002e // add	x14, x1, x12
	WORD $0xfa4f3042 // ccmp	x2, x15,
	WORD $0x1a9f27eb // cset	w11, lo
	WORD $0xeb0f01df // cmp	x14, x15
	WORD $0xfa5031a2 // ccmp	x13, x16,
	WORD $0x54fffd03 // b.lo	.LBB1_10
	WORD $0x3707fceb // tbnz	w11,
	WORD $0x927ef54b // and	x11, x10,
	WORD $0xfd400040 // ldr	d0, [x2]
	WORD $0x9100418d // add	x13, x12,
	WORD $0x8b090169 // add	x9, x11, x9
	WORD $0x8b0d000c // add	x12, x0, x13
	WORD $0x8b0d002d // add	x13, x1, x13
	WORD $0x927ef54e // and	x14, x10,

LBB1_16:
	WORD $0xad7f89a1 // ldp	q1, q2, [x13,
	WORD $0xf10011ce // subs	x14, x14,
	WORD $0x910081ad // add	x13, x13,
	WORD $0x4fc09021 // fmul	v1.2d, v1.2d, v0.d[0]
	WORD $0x4fc09042 // fmul	v2.2d, v2.2d, v0.d[0]
	WORD $0xad3f8981 // stp	q1, q2, [x12,
	WORD $0x9100818c // add	x12, x12,
	WORD $0x54ffff21 // b.ne	.LBB1_16
	WORD $0xeb0b015f // cmp	x10, x11
	WORD $0x54fffac1 // b.ne	.LBB1_10
	WORD $0x17ffffdf // b	.LBB1_12

TEXT ·dot_f64(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD res+16(FP), R2
	MOVD len+24(FP), R3
	WORD $0xa9bf7bfd    // stp	x29, x30, [sp,
	WORD $0xf9400068    // ldr	x8, [x3]
	WORD $0x910003fd    // mov	x29, sp
	WORD $0x12000109    // and	w9, w8,
	WORD $0x7100011f    // cmp	w8,
	WORD $0x5a895529    // cneg	w9, w9, mi
	WORD $0x4b09010a    // sub	w10, w8, w9
	WORD $0x7100215f    // cmp	w10,
	WORD $0x5400010a    // b.ge	.LBB2_2
	WORD $0x6f00e402    // movi	v2.2d,
	WORD $0x6f00e401    // movi	v1.2d,
	WORD $0x2a1f03eb    // mov	w11, wzr
	WORD $0x6f00e400    // movi	v0.2d,
	WORD $0x6b0a017f    // cmp	w11, w10
	WORD $0x5400030b    // b.lt	.LBB2_5
	WORD $0x14000021    // b	.LBB2_7

LBB2_2:
	WORD $0x6f00e400 // movi	v0.2d,
	WORD $0x6f00e401 // movi	v1.2d,
	WORD $0x9100800c // add	x12, x0,
	WORD $0x6f00e402 // movi	v2.2d,
	WORD $0x6f00e403 // movi	v3.2d,
	WORD $0x9100802d // add	x13, x1,
	WORD $0x5280010b // mov	w11,

LBB2_3:
	WORD $0xad7f1584 // ldp	q4, q5, [x12,
	WORD $0x9100216b // add	x11, x11,
	WORD $0xad7f1da6 // ldp	q6, q7, [x13,
	WORD $0xeb0a017f // cmp	x11, x10
	WORD $0xacc24590 // ldp	q16, q17, [x12],
	WORD $0xacc24db2 // ldp	q18, q19, [x13],
	WORD $0x4e64ccc0 // fmla	v0.2d, v6.2d, v4.2d
	WORD $0x4e65cce1 // fmla	v1.2d, v7.2d, v5.2d
	WORD $0x4e70ce42 // fmla	v2.2d, v18.2d, v16.2d
	WORD $0x4e71ce63 // fmla	v3.2d, v19.2d, v17.2d
	WORD $0x54fffec9 // b.ls	.LBB2_3
	WORD $0x4e62d462 // fadd	v2.2d, v3.2d, v2.2d
	WORD $0x5100216b // sub	w11, w11,
	WORD $0x6b0a017f // cmp	w11, w10
	WORD $0x5400016a // b.ge	.LBB2_7

LBB2_5:
	WORD $0xd37d7d6d // ubfiz	x13, x11,
	WORD $0x2a0b03eb // mov	w11, w11
	WORD $0x8b0d002c // add	x12, x1, x13
	WORD $0x8b0d000d // add	x13, x0, x13

LBB2_6:
	WORD $0x3cc105a3 // ldr	q3, [x13],
	WORD $0x9100096b // add	x11, x11,
	WORD $0x3cc10584 // ldr	q4, [x12],
	WORD $0xeb0a017f // cmp	x11, x10
	WORD $0x4e63cc80 // fmla	v0.2d, v4.2d, v3.2d
	WORD $0x54ffff63 // b.lo	.LBB2_6

LBB2_7:
	WORD $0x4e60d420 // fadd	v0.2d, v1.2d, v0.2d
	WORD $0x7100013f // cmp	w9,
	WORD $0x4e60d440 // fadd	v0.2d, v2.2d, v0.2d
	WORD $0x7e70d800 // faddp	d0, v0.2d
	WORD $0x540000ed // b.le	.LBB2_9
	WORD $0x93407d08 // sxtw	x8, w8
	WORD $0xd37df108 // lsl	x8, x8,
	WORD $0xd1002108 // sub	x8, x8,
	WORD $0xfc686801 // ldr	d1, [x0, x8]
	WORD $0xfc686822 // ldr	d2, [x1, x8]
	WORD $0x1f420020 // fmadd	d0, d1, d2, d0

LBB2_9:
	WORD $0xfd000040 // str	d0, [x2]
	WORD $0xa8c17bfd // ldp	x29, x30, [sp],
	RET
