//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.

package asm

import "unsafe"

//go:noescape
func vec_mul_f64(dst, a, b, len unsafe.Pointer)

//go:noescape
func vec_scale_f64(dst, a, scalar, len unsafe.Pointer)

//go:noescape
func dot_f64(a, b, res, len unsafe.Pointer)
